QMAKE=qmake

PROJECT_NAME=Klondike
PROJECT_FILE=src/$(PROJECT_NAME).pro

GUI_BUILD_DIR=build/tmp/gui
GUI_RELEASE_DIR=build/release/gui
GUI_MAKEFILE=Makefile.gui
GUI_BINARY=hra2017

CLI_BUILD_DIR=build/tmp/cli
CLI_RELEASE_DIR=build/release/cli
CLI_MAKEFILE=Makefile.cli
CLI_BINARY=hra2017-cli
